[[constraint]]
  name = "github.com/awalterschulze/gographviz"
  version = "2.0.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gruntwork-io/terratest"
  version = "0.10.1"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/terraform"

[[constraint]]
  branch = "master"
  name = "github.com/mingfang/terraform-provider-k8s"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "master"
  name = "k8s.io/cli-runtime"

[[constraint]]
  branch = "master"
  name = "k8s.io/client-go"

[[constraint]]
  branch = "master"
  name = "k8s.io/kube-openapi"

[prune]
  go-tests = true
  unused-packages = true
